

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."monthly_income" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date" timestamp with time zone
);


ALTER TABLE "public"."monthly_income" OWNER TO "postgres";


COMMENT ON TABLE "public"."monthly_income" IS 'income per month for analysis';



ALTER TABLE "public"."monthly_income" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."monthly_income_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."raw_transactions" (
    "id" bigint NOT NULL,
    "description" "text",
    "amount" numeric,
    "transaction_date" timestamp with time zone,
    "posting_date" timestamp with time zone,
    "reference_number" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "isPaid" boolean DEFAULT false,
    "category" "text" DEFAULT 'None'::"text"
);


ALTER TABLE "public"."raw_transactions" OWNER TO "postgres";


COMMENT ON TABLE "public"."raw_transactions" IS 'Financial transactions raw data uploaded from clients';



ALTER TABLE "public"."raw_transactions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."raw_transactions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."monthly_income"
    ADD CONSTRAINT "monthly_income_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."raw_transactions"
    ADD CONSTRAINT "raw_transactions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."raw_transactions"
    ADD CONSTRAINT "raw_transactions_reference_number_key" UNIQUE ("reference_number");



CREATE POLICY "Enable insert for authenticated users only" ON "public"."raw_transactions" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."raw_transactions" FOR SELECT USING (true);



CREATE POLICY "Enable update access for all users" ON "public"."raw_transactions" FOR UPDATE USING (true);



ALTER TABLE "public"."monthly_income" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."raw_transactions" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



































































































































































































GRANT ALL ON TABLE "public"."monthly_income" TO "anon";
GRANT ALL ON TABLE "public"."monthly_income" TO "authenticated";
GRANT ALL ON TABLE "public"."monthly_income" TO "service_role";



GRANT ALL ON SEQUENCE "public"."monthly_income_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."monthly_income_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."monthly_income_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."raw_transactions" TO "anon";
GRANT ALL ON TABLE "public"."raw_transactions" TO "authenticated";
GRANT ALL ON TABLE "public"."raw_transactions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."raw_transactions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."raw_transactions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."raw_transactions_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
